; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:custom_g474re]
platform = ststm32
board = custom_g474re
framework = arduino
upload_protocol = dfu
monitor_speed = 115200

build_flags =
    -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
    -D USBCON
    -D HAL_PCD_MODULE_ENABLED
    -D VARIANT_H=\"variant_generic.h\"
    -DADC_SAMPLINGTIME=ADC_SAMPLETIME_247CYCLES_5

lib_deps =
    adafruit/Adafruit BusIO@^1.16.1

extra_scripts = pre:create_variant.py
