# Scans the firmware for test programs and for main.cpp's RUN_TEST, at configure time.
#
#   BUCKY_SIM_TEST_NAMES   every `void testXxx(const TestContext& ...)` *defined* in src/tests
#   BUCKY_SIM_RUN_TEST     the plain identifier main.cpp's `#define RUN_TEST` names, or ""
#
# and writes ${CMAKE_BINARY_DIR}/generated/programs_generated.h. Re-runs when the scanned files
# change (CMAKE_CONFIGURE_DEPENDS).

file(GLOB_RECURSE _test_sources CONFIGURE_DEPENDS "${FIRMWARE_DIR}/tests/*.cpp")
set(BUCKY_SIM_TEST_NAMES "")
foreach(_src IN LISTS _test_sources)
    file(READ "${_src}" _text)
    string(REGEX MATCHALL "void[ \t\r\n]+test[A-Za-z0-9_]*[ \t\r\n]*\\([ \t\r\n]*const[ \t\r\n]+TestContext[ \t\r\n]*&[^)]*\\)[ \t\r\n]*{" _defs "${_text}")
    foreach(_def IN LISTS _defs)
        string(REGEX REPLACE "^void[ \t\r\n]+(test[A-Za-z0-9_]*).*$" "\\1" _name "${_def}")
        list(APPEND BUCKY_SIM_TEST_NAMES "${_name}")
    endforeach()
endforeach()
list(REMOVE_DUPLICATES BUCKY_SIM_TEST_NAMES)
list(SORT BUCKY_SIM_TEST_NAMES)

set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${FIRMWARE_DIR}/main.cpp")
file(READ "${FIRMWARE_DIR}/main.cpp" _main)
set(BUCKY_SIM_RUN_TEST "")
# Only an uncommented `#define RUN_TEST <identifier>` counts.
string(REGEX MATCH "(^|\n)[ \t]*#[ \t]*define[ \t]+RUN_TEST[ \t]+([A-Za-z_][A-Za-z0-9_]*)[ \t]*(//[^\n]*)?(\n|$)" _m "${_main}")
if(_m)
    set(BUCKY_SIM_RUN_TEST "${CMAKE_MATCH_2}")
endif()
string(REGEX MATCH "(^|\n)[ \t]*#[ \t]*define[ \t]+RUN_TEST[ \t]*[^ \t\n]" _any "${_main}")
if(_any AND NOT BUCKY_SIM_RUN_TEST)
    message(WARNING "main.cpp's RUN_TEST is not a plain test name; test programs run through the "
                    "simulator's own prelude instead of main()")
endif()
if(BUCKY_SIM_RUN_TEST AND NOT BUCKY_SIM_RUN_TEST IN_LIST BUCKY_SIM_TEST_NAMES)
    message(WARNING "main.cpp's RUN_TEST (${BUCKY_SIM_RUN_TEST}) is not a defined test")
endif()

set(_x "")
foreach(_name IN LISTS BUCKY_SIM_TEST_NAMES)
    string(APPEND _x " X(${_name})")
endforeach()
file(CONFIGURE OUTPUT "${CMAKE_BINARY_DIR}/generated/programs_generated.h" CONTENT
"// GENERATED by robot/sim/cmake/gen_programs.cmake from robot/src/tests. Do not edit.
#pragma once
#define BUCKY_SIM_TESTS(X)${_x}
" @ONLY)
message(STATUS "bucky sim: programs = ${BUCKY_SIM_TEST_NAMES}; RUN_TEST = '${BUCKY_SIM_RUN_TEST}'")
