#!/usr/bin/env python3
"""Copy / generate the stm32duino pieces the host simulator needs.

The firmware includes a handful of Arduino-STM32 core headers (``PinNames.h``, ``pinmap.h``,
``PeripheralPins.h``, ``Print.h``, ``WString.h``, …). Rather than hand-copying them, this script
pulls them from the PlatformIO package the real firmware builds against, so pin numbering,
``String`` formatting and ``Print`` number/float formatting are byte-for-byte the target's.

Outputs (committed, regenerate after a framework upgrade)::

    robot/sim/vendor/stm32duino/   copied unmodified, except Print.cpp (see PRINT_PATCHES)
    robot/sim/boards/<board>/      PinNamesVar.h (copied) + PeripheralPins.cpp (generated:
                                   PinMap_TIM / PinMap_ADC with STM_PIN_DATA_EXT resolved)

Usage::

    python robot/sim/tools/gen_vendor.py [--framework ~/.platformio/packages/framework-arduinoststm32]
"""
from __future__ import annotations

import argparse
import json
import re
import shutil
from pathlib import Path

SIM = Path(__file__).resolve().parents[1]
DEFAULT_FRAMEWORK = Path.home() / ".platformio/packages/framework-arduinoststm32"

SRCWRAPPER = [
    "PinNames.h", "PinNamesTypes.h", "PortNames.h", "pinmap.h", "PeripheralPins.h",
]
CORE = [
    "Print.h", "Printable.h", "WString.h", "WString.cpp", "itoa.h", "itoa.c",
    "avr/dtostrf.h", "avr/dtostrf.c", "avr/pgmspace.h",
]

BOARDS = {
    # sim board name -> (variant dir, maps to generate)
    "h562rg": ("STM32H5xx/H562R(G-I)T", ("PinMap_TIM", "PinMap_ADC")),
}

# Print.cpp's printf goes through newlib's vdprintf((int)this, …), a pointer→int cast that
# breaks on 64-bit hosts, and it defines a weak _write() syscall. Route printf through
# sim_vdprintf (vsnprintf + write) and drop the syscall; everything else is untouched.
PRINT_PATCHES = [
    (re.compile(r'extern "C" \{\s*__attribute__\(\(weak\)\)\s*int _write\(.*?\n\}\n', re.S),
     'extern "C" int sim_vdprintf(Print* p, const char* fmt, va_list ap);  // sim: Print.cpp\n'),
    (re.compile(r"vdprintf\(\(int\)this, "), "sim_vdprintf(this, "),
]

HEADER = "// GENERATED by robot/sim/tools/gen_vendor.py from {src} ({version}). Do not edit.\n"


def framework_version(fw: Path) -> str:
    try:
        return "framework-arduinoststm32 " + json.loads((fw / "package.json").read_text())["version"]
    except (OSError, KeyError, ValueError):
        return "framework-arduinoststm32 (unknown version)"


def copy_vendor(fw: Path, out: Path) -> None:
    out.mkdir(parents=True, exist_ok=True)
    for name in SRCWRAPPER:
        shutil.copyfile(fw / "libraries/SrcWrapper/inc" / name, out / name)
    for name in CORE:
        dst = out / name
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(fw / "cores/arduino" / name, dst)

    text = (fw / "cores/arduino/Print.cpp").read_text()
    for pattern, repl in PRINT_PATCHES:
        text, n = pattern.subn(repl, text)
        if n == 0:
            raise SystemExit(f"Print.cpp patch {pattern.pattern!r} no longer matches")
    (out / "Print.cpp").write_text(
        "// Patched copy (see gen_vendor.py PRINT_PATCHES): printf → sim_vdprintf.\n" + text)


ENTRY = re.compile(
    r"\{\s*(?P<pin>\w+)\s*,\s*(?P<periph>\w+)\s*,\s*STM_PIN_DATA_EXT\(\s*(?P<mode>\w+)\s*,"
    r"\s*(?P<pull>\w+)\s*,\s*(?P<af>\w+)\s*,\s*(?P<chan>\d+)\s*,\s*(?P<inv>\d+)\s*\)\s*\}"
)
PULLS = {"GPIO_NOPULL": 0, "GPIO_PULLUP": 1, "GPIO_PULLDOWN": 2}


def parse_map(source: str, name: str) -> list[dict]:
    m = re.search(rf"const PinMap {name}\[\] = \{{(.*?)\n\}};", source, re.S)
    if m is None:
        raise SystemExit(f"{name} not found in PeripheralPins.c")
    body = m.group(1)
    entries = []
    for line in body.splitlines():
        line = line.split("//")[0]
        e = ENTRY.search(line)
        if e is None:
            continue
        af = e["af"]
        afnum = int(af) if af.isdigit() else int(re.match(r"GPIO_AF(\d+)_", af).group(1))
        entries.append({
            "pin": e["pin"], "periph": e["periph"], "mode": e["mode"],
            "pull": PULLS[e["pull"]], "af": afnum, "chan": int(e["chan"]), "inv": int(e["inv"]),
        })
    return entries


def gen_board(fw: Path, board: str) -> None:
    variant, maps = BOARDS[board]
    vdir = fw / "variants" / variant
    out = SIM / "boards" / board
    out.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(vdir / "PinNamesVar.h", out / "PinNamesVar.h")

    source = (vdir / "PeripheralPins.c").read_text()
    lines = [
        HEADER.format(src=f"variants/{variant}/PeripheralPins.c", version=framework_version(fw)),
        "#include <PeripheralPins.h>\n#include <stm32_def.h>\n",
    ]
    for name in maps:
        lines.append(f"const PinMap {name}[] = {{")
        for e in parse_map(source, name):
            lines.append(
                f"  {{{e['pin']}, {e['periph']}, STM_PIN_DATA_EXT({e['mode']}, {e['pull']}, "
                f"{e['af']}, {e['chan']}, {e['inv']})}},")
        lines.append("  {NC, nullptr, 0}\n};\n")
    (out / "PeripheralPins.cpp").write_text("\n".join(lines))


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--framework", type=Path, default=DEFAULT_FRAMEWORK)
    args = ap.parse_args()
    fw = args.framework.expanduser()
    if not (fw / "cores/arduino").is_dir():
        raise SystemExit(f"stm32duino framework not found at {fw}")
    copy_vendor(fw, SIM / "vendor/stm32duino")
    (SIM / "vendor/stm32duino/VERSION").write_text(framework_version(fw) + "\n")
    for board in BOARDS:
        gen_board(fw, board)
    print(f"vendored {framework_version(fw)} into {SIM / 'vendor'}")


if __name__ == "__main__":
    main()
